# ------------------------------------------------------------------------------
# base Jekyll configuration
# ------------------------------------------------------------------------------

# description
name: "POBP"
description: "WIP"
keywords: "wip"
author: "Leszek Pietrzak"

# address settings
rootSiteUrl: "http://smutnyleszek.com"
baseurl: "http://pobp.smutnyleszek.com"
permalink: /projects/:title
imagesPath: "/dist/images/"

# urls
googleFontsCode: family=Source+Sans+Pro:400,700,400italic,700italic&subset=latin,latin-ext

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# pull includes from other directory
includes_dir: src
exclude:
    # disabled src, as it breaks --watch (see includes_dir)
    # - src
    - bin
    - node_modules
    - LICENSE
    - README.md
    - package.json

# ------------------------------------------------------------------------------
# page categories and custom collections
# ------------------------------------------------------------------------------

collections:
    content_kajaki:
        output: true
        permalink: /kajaki/:path/
    content_projekty:
        output: true
        permalink: /projekty/:path/
    content_zabytki:
        output: true
        permalink: /zabytki/:path/
defaults:
    - scope:
        path: ''
        type: content_kajaki
      values:
        layout: project
        category: kajaki
    - scope:
        path: ''
        type: content_zabytki
      values:
        layout: project
        category: zabytki
    - scope:
        path: ''
        type: content_projekty
      values:
        layout: project
        category: projekty
