# description
name: "POBP"
description: "WIP"
keywords: "wip"
author: "Leszek Pietrzak"

# address settings
rootSiteUrl: "http://smutnyleszek.com"
baseurl: "http://pobp.smutnyleszek.com"
permalink: /projects/:title
imagesPath: "/dist/images/"

# urls
googleFontsCode: family=Source+Sans+Pro:400,700,400italic,700italic&subset=latin,latin-ext

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# excludes
exclude:
    # disabled src, as it breaks --watch (see includes_dir below)
    # - src
    - bin
    - node_modules
    - LICENSE
    - README.md
    - package.json

# pull includes from other directory
includes_dir: src
